### ISSUE TITLE
HMIS Roadmap

### ISSUE THREAD

**Issue by gigincg** [ohcnetwork/legacy-docs#14]
This issue serves as a comprehensive placeholder for the ideas/features for implementation in our long-term roadmap. Before being taken up for active development, each item needs to be detailed in a separate issue within this docs repository. Following this, a RFC (Request for Change) will be drafted and submitted as a Pull Request (PR) to the docs repository for review and collaboration, outline the changes required on models and APIs for building this feature. Upon approval, an issue will be created in the respective application's repository, marking the beginning of the development phase. 

Billing Pre-requisites
- [ ] Procedures - Scheduling - Team - Master List | Planned/Execution | Requires Generic Scheduling
- [ ] Asset/Bed Utilization (Ventilators) | consultation_bed_asset
- [ ] Investigations | Merge Sample flow & Investigations & Investigation Recommendations flow | maybe Rebuild? | Planned/Execution
- [ ] Medicine & Consumables | Planned/Execution
- [ ] Pharmacy/Inventory

Platform Features
- [ ] Citizen v2 with ABDM
- [ ] DICOM Viewer on care_fe | S3 based DICOM file management
- [ ] IM Wrapper for CARE/CARE bot (Ideally start with Whatsapp)
- [x] Middleware Rewrite in Django | Active GSoC Project

Consultation/Encounter Related
- [ ] Refactor `patient_consultation` as `patient_encounter`
- [ ] Create Consultation/Appointments with Encounters | Requires Generic Scheduling
- [ ] Build out ABDM Scan & Share for Creating Appointments

Long Term
- [ ] Billing App
- [ ] Billing Export to Odoo or similar CRM/Accounting System
- [ ] RBAC
- [ ] Plugin Architecture
- [ ] Events Archival
- [x] Scribe | Internal rewrite
- [ ] Generic Scheduling System | for Consultations, Doctors, Resources, Locations etc
