### ISSUE TITLE
ABDM Integration

### ISSUE THREAD

**Issue by khavinshankar** [ohcnetwork/legacy-docs#21]
This EPIC issue serves as a placeholder to track the changes and features to be implemented under ABDM Integration.

- [x] #22
- [ ] Write tests for ABDM data mapping
- [ ] Write tests for ABDM flows
- [ ] Show user-friendly error messages
- [ ] Implement new counterparts of the APIs and deprecate the older ones
- [ ] Fix the scan and share flow
- [ ] Implement the pending M1 flows
    - [ ] Creation and Verification using Aadhaar Demographics
    - [ ] Creation using Aadhaar Biometric
    - [ ] Creation using a Driving License
    - [ ] Profile Update
- [ ] Fix Download ABHA card flow
- [ ] Scope out integrating HFR (Health Facility Registry) and HPR (Health Professional Registry)
- [ ] Improve the UI UX of the incoming data displayed from ABDM
- [ ] Improve the FHIR mapping of the data sent out via ABDM
