### ISSUE TITLE
Separate ABDM into a plug

### ISSUE THREAD

**Issue by khavinshankar** [ohcnetwork/legacy-docs#22]
**Todo:**
- [x] Clean up the usage or access of the abdm app inside the facility app
  - [x] `care/facility/models/patient.py`
      ```py
      abha_number = models.OneToOneField(
          AbhaNumber, on_delete=models.SET_NULL, null=True, blank=True
      )  
     # TODO: move this relation inside Abha Number model

      patient = models.OneToOneField(
          Patient, on_delete=models.CASCADE, null=True, blank=True
      ) # VERIFY: abha number is deleted when patient is deleted and not vice versa

      # TODO: Add the necessary migration
      ```
  - [x]  `care/facility/api/serializers/patient.py`
      ```py
      abha_number = ExternalIdSerializerField(
        queryset=AbhaNumber.objects.all(), required=False, allow_null=True
      )
      abha_number_object = AbhaNumberSerializer(source="abha_number", read_only=True)

      # TODO: create an extended serializer in abdm plug for internal use and in the frontend seperate out the api calls for patient and abha number
      ```
  - [x] `care/facility/api/serializers/patient_consultation.py`
      ```py
      if patient.abha_number:
          abha_number = patient.abha_number
          try:
              AbdmGateway().fetch_modes(
                  {
                      "healthId": abha_number.abha_number,
                      "name": abha_number.name,
                      "gender": abha_number.gender,
                      "dateOfBirth": str(abha_number.date_of_birth),
                      "consultationId": abha_number.external_id,
                      "purpose": "LINK",
                  }
              )
          except Exception:
              pass
       # TODO: use signals to intercept post_save inside plug

      # in signals/consultation.py
      from django.db.models.signals import post_save
      from django.dispatch import receiver
      from facility.models import Consultation  # Import the Consultation model from the facility app

      @receiver(post_save, sender=Consultation)
      def create_care_context(sender, instance, created, **kwargs):
          patient = instance.patient
          abha_number = AbhaNumber.objects.filter(patient__external_id=patient.id)
          if created:
              try:
                  AbdmGateway().fetch_modes(
                      {
                          "healthId": abha_number.abha_number,
                          "name": abha_number.name,
                          "gender": abha_number.gender,
                          "dateOfBirth": str(abha_number.date_of_birth),
                          "consultationId": abha_number.external_id,
                          "purpose": "LINK",
                      }
                  )
              except Exception:
                  pass 
      ```
- [x] Move envs and routes to the plug

**Extras:**
- [ ] Clean up fetch_modes, init, confirm flow
- [ ] Refactor M1 & M2 into the structure used in M3
- [ ] Add standard suffixes for the routes of abdm callback apis
