### ISSUE TITLE
Enhance Existing Inventory System to Support Dynamic Management

### ISSUE THREAD

**Issue by nihal467** [ohcnetwork/legacy-docs#38]
## Project Detail

CARE is a centralized capacity management and patient management system, central to the 10BedICU Project, integrating patients, doctors, hospitals, labs, specialized treatment centers, hospital administrators, and shifting control cells. Hospitals update crucial information about their assets, providing district administration with a comprehensive view of the healthcare system via smart dashboards. CARE digitizes patient records, streamlines workflows for pandemic management, and is deployed in remote areas, enabling TeleICU services for underserved citizens. It revolutionizes healthcare management, enhancing efficiency, accessibility, and patient outcomes.

## Features To Be Implemented

This project outlines enhancements to the existing facility inventory management system. This feature will assist users in managing facility inventory and pharmacy. The features expected to be achieved are outlined below:

- [ ] **Dynamic Inventory Management:** Allow adding and removing items dynamically to support pharmacy and inventory management.
- [ ] **Facility and Location Tracking:** Implement a log to track stock and issuance locations within the facility, e.g.,Store room, pharmacy, ICU, ward etc
- [ ] **Real-time Stock Levels:** Ensure real-time visibility of stock levels for efficient management.
- [ ] **Automated Reordering:** Integrate automated reordering based on minimum stock levels and rate of consumption. (Low Stock items on top of the list)
- [ ] **Report Generation:** Add export functionality to generate csv report (Inventory Name, Location, Current Stock, Minimum Stock Required, Last Updated Date)

## Learning Path

|  | Details |
| :---:  | :---:  |
| Complexity       | Medium |
| Required Skills | ReactJS, NodeJS, TypeScript, Django |
| Mentors            | @nihal467 , @vigneshhari , @khavinshankar , @rithviknishad , @gigincg , @Ashesh3 , @sainak |
| Project Size      | 350 hours |

## Link to documentation for Product Set-Up

1. For setting up the frontend, please refer to the readme file available at: https://github.com/coronasafe/care_fe
2. For setting up the backend, please refer to the readme file available at: https://github.com/coronasafe/care

## Acceptance Criteria

- All the CI/CD workflows should pass.
- Code is logically structured for long-term project sustainability.
- Proper descriptions should be included for review purposes.
- QA and Code Review

## Milestone

- [ ] Get to know CARE as a product and understand the workflow.
- [ ] Understand the user-level requirements and come up with a design.
- [ ] Design and implement the updated UI
- [ ] Complete functionality of Enhanced Inventory Management System
- [ ] Implement a Basic Cypress automation test to test functionality
- [ ] Optimise and improve UX
- [ ] Review and QA

**Comment by rithviknishad** [comment]
Related stale issue: https://github.com/coronasafe/care_fe/issues/6612

cc: @khavinshankar

**Comment by khavinshankar** [comment]
Discussed the requirements in the engineering call, have to discuss further on how inventory items have to be linked the master list.

Eg: When we track medicines and consumables in inventory, how should they be linked with actual models in the care (polymorphic relations or json meta).

What are other possible items in the inventory that could be linked with models in care?


cc: @gigincg

**Comment by 2003Aditya** [comment]
@rithviknishad can i work on this project?
