### ISSUE TITLE
Generic Scheduling System For CARE

### ISSUE THREAD

**Issue by nihal467** [ohcnetwork/legacy-docs#53]
## Requirements

Develop a scheduling system within CARE that supports managing outpatient (OP) tickets or slots. Each doctor should be able to configure their availability, specifying the days they will be available and either the number of slots or the duration they will be available for. Appointments can then be booked within these availability windows. The system should offer both an appointment-based and a token-based model, ensuring that the number of tokens matches the available slots. Additionally, the scheduling table should be flexible enough to handle bookings for different locations, such as operation theatres, cath labs, etc., which will be represented as location entities in CARE.

Appointments may include multiple participants or be linked to other objects. For example, a procedure could be an object with a team associated with it, and the team would consist of the participants involved in the appointment.

Moreover, a receptionist flow needs to be created for managing both the booking of appointments and the assignment of tokens, specifically for OP consultations. The receptionist flow should streamline the booking process for outpatient services.

## Roadmap

- [ ] Create a Care Enhancement Proposal (CEP) outlining the APIs & Models for enabling Scheduling
- [ ] Get the CEP reviewed from the Core Team
- [ ] Expand the CEP with planned Mockups
- [ ] Design and Implement the models, APIs & UI

**Comment by r-nikhilkumar** [comment]
@nihal467, @rithviknishad  It's really interesting, can I look for it?

**Comment by nihal467** [comment]
Hey everyone,

Thank you for showing interest in the projects. I would like to inform you that we have scheduled **EOD calls on Zoom** from Monday to Saturday at **7:30 PM** to discuss your work and address any doubts with the core team. Alternatively, feel free to use our **#care_general** Slack channel.

The meeting links will be shared in our **#reminder** channel in our Slack workspace. 

**Link to join the Slack:** [Slack Workspace](https://join.slack.com/t/rebuildearth/shared_invite/zt-2blycdt83-yvoJRsa10QDhE9WFiwoVkg)

Meanwhile, please explore the care platform and familiarize yourself with its features. Feel free to play around with it and assign any open issues as you see fit.

**Comment by JohnLu2004** [comment]
@nihal467 @vigneshhari 
CARE sounds like a comprehensive system for hospital management, and I would love to contribute to the project as a Google Summer of Code Developer. I've joined the slack workspace. Is there anything else I can do to learn more about it or learn how to contribute?

**Comment by nihal467** [comment]
> @nihal467 @vigneshhari CARE sounds like a comprehensive system for hospital management, and I would love to contribute to the project as a Google Summer of Code Developer. I've joined the slack workspace. Is there anything else I can do to learn more about it or learn how to contribute?

@JohnLu2004 https://rebuildearth.slack.com/archives/CC9LWNG1K/p1708600891675389 check this message in the announcement channel for more info

**Comment by Sulochan-khadka** [comment]
Hey @nihal467 , may you assign me this issue so that I can fix this as soon as possible.

**Comment by gigincg** [comment]
@khavinshankar You've been working on docs for Scheduling right? Can you update the PR in the docs repo and update here?

**Comment by khavinshankar** [comment]
Docs of the initial ideation of scheduling can be found at https://github.com/coronasafe/docs/pull/34

Preview: https://docs-git-scheduling-ohcnetwork.vercel.app/docs/care/CEP/Draft/scheduling

**Comment by Sulochan-khadka** [comment]
Is this project completed @rithviknishad @gigincg ? I would like to work on it if it is not completed.

**Comment by rithviknishad** [comment]
Hey @Sulochan-khadka 

This is a larger piece that is to be built, we would create related smaller sub-issues and mark some of them as "good first issues". You can look out for them in the coming weeks.

Feel free to take up other good first issues in the meantime 😄 
https://github.com/ohcnetwork/care_fe/contribute
